name: i69n
description: Simple internationalization tool for Dart and Flutter, based on YAML files and source generation.
version: 0.1.0
homepage: https://github.com/fnx-io/i69n
author: Tomas Zverina <t@fnx.io>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  build: ^1.0.0
  # Not imported in code, but used to constrain `build.yaml` requirements
  build_config: ^0.4.1
  yaml: ^2.1.15

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
  build_runner: ^1.0.0
  build_web_compilers: ^1.0.0

